### ISSUE TITLE
nut_server fails to compile on ESPHome 2026.8.2 — "expected primary-expression before '(' token" on socket()

### ISSUE THREAD

**Issue by angelosan** [bullshit/esphome-components#34]
## The problem

`nut_server.cpp` fails to compile on ESPHome 2026.8.0 with a namespace/symbol 
resolution error on the `socket()` call.

## Which version of ESPHome has the issue?

2026.8.2

## Component version / source

github://bullshit/esphome-components, components: [ups_hid, nut_server]

## Steps to reproduce

Compile any config using `nut_server:` on ESPHome 2026.8.0. Note: I applied the 
workaround from #15 (explicitly declaring `device_class`/`unit_of_measurement`/
`accuracy_decimals` on all ups_hid sensors) to get past the earlier compile error — 
that workaround succeeded, and the build proceeded much further, but then failed on 
this new, apparently unrelated error in `nut_server.cpp`.

## Anything in the logs that might be useful for us?

```text
[1211/1273] Building CXX object esp-idf/src/CMakeFiles/__idf_src.dir/esphome/components/nut_server/nut_server.cpp.obj
FAILED: esp-idf/src/CMakeFiles/__idf_src.dir/esphome/components/nut_server/nut_server.cpp.obj
../src/esphome/components/nut_server/nut_server.cpp: In member function 'bool esphome::nut_server::NutServerComponent::start_server()':
../src/esphome/components/nut_server/nut_server.cpp:76:26: error: expected primary-expression before '(' token
   76 |   server_socket_ = socket(AF_INET, SOCK_STREAM, 0);
      |                          ^
```

## My guess at the cause (not a C++ developer, take with a grain of salt)

`nut_server.cpp` is presumably inside `namespace esphome { namespace nut_server { ... } }`. 
ESPHome also has its own internal `esphome::socket` component/namespace (visible in the 
same build log, right after this error: `bsd_sockets_impl.cpp` from that component gets 
compiled next). My guess is that on 2026.8.0, something changed so that the 
`esphome::socket` namespace becomes visible/ambiguous inside `nut_server`'s scope, and the 
compiler tries to resolve the bare `socket(...)` call against that namespace instead of 
the global BSD `socket()` function, since a namespace isn't callable.

If that's correct, qualifying the call with the global scope operator 
(`::socket(AF_INET, SOCK_STREAM, 0);`) in `nut_server.cpp` might fix it, but I haven't 
verified this myself.

## Environment

* ESPHome: 2026.8.2
* ESP-IDF: 5.5.2 (via pioarduino/platform-espressif32 @ 55.03.37)
* Board: ESP32-S3-WROOM-1 N16R8, generic clone (44-pin, dual USB-C)

**Comment by kramttocs** [comment]
Same as #23
